-- MySQL Script generated by MySQL Workbench
-- Sat 04 Jul 2020 02:48:04 PM WAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema easytrack
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `easytrack` ;

-- -----------------------------------------------------
-- Schema easytrack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easytrack` DEFAULT CHARACTER SET latin1 ;
USE `easytrack` ;

-- -----------------------------------------------------
-- Table `easytrack`.`agendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`agendas` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`agendas` (
  `site_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `start` DATETIME NOT NULL,
  `status` ENUM('1', '0') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `end` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`bills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`bills` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`bills` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `site_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `code` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `status` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '0',
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `bills_code_unique` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`users` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `site_id` BIGINT(20) NULL DEFAULT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `username` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `tel` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `cni_number` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `contact_name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `contact_tel` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `photo` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `address` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `password` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `is_admin` ENUM('1', '2', '3') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 603;


-- -----------------------------------------------------
-- Table `easytrack`.`snacks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`snacks` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`snacks` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tel1` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `tel2` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `town` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `street` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `logo` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `snacks_email_unique` (`email` ASC),
  UNIQUE INDEX `snacks_slug_unique` (`slug` ASC),
  INDEX `snacks_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `snacks_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `easytrack`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11;


-- -----------------------------------------------------
-- Table `easytrack`.`sites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`sites` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`sites` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `snack_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tel1` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `tel2` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `town` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `street` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sites_name_unique` (`name` ASC),
  UNIQUE INDEX `sites_slug_unique` (`slug` ASC),
  INDEX `sites_snack_id_foreign` (`snack_id` ASC),
  CONSTRAINT `sites_snack_id_foreign`
    FOREIGN KEY (`snack_id`)
    REFERENCES `easytrack`.`snacks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 31;


-- -----------------------------------------------------
-- Table `easytrack`.`budgets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`budgets` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`budgets` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `site_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `amount` INT(11) NOT NULL,
  `type` ENUM('fixed', 'variable') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT 'fixed',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `budgets_site_id_foreign` (`site_id` ASC),
  CONSTRAINT `budgets_site_id_foreign`
    FOREIGN KEY (`site_id`)
    REFERENCES `easytrack`.`sites` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`categories` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`categories` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6;


-- -----------------------------------------------------
-- Table `easytrack`.`failed_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`failed_jobs` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `connection` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `queue` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `payload` LONGTEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `exception` LONGTEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`invoices` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`invoices` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `site_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `code` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `status` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`messages` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`messages` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sender` INT(11) NOT NULL,
  `receiver` INT(11) NOT NULL,
  `status` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '0',
  `message` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `file` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`migrations` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32;


-- -----------------------------------------------------
-- Table `easytrack`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`notifications` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`notifications` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `site_id` BIGINT(20) NULL DEFAULT NULL,
  `snack_id` BIGINT(20) NULL DEFAULT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  `type` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `text` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `status` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `action` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`oauth_access_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`oauth_access_tokens` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`oauth_access_tokens` (
  `id` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `client_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `scopes` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_access_tokens_user_id_index` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`oauth_auth_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`oauth_auth_codes` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`oauth_auth_codes` (
  `id` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `client_id` BIGINT(20) UNSIGNED NOT NULL,
  `scopes` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_auth_codes_user_id_index` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`oauth_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`oauth_clients` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`oauth_clients` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `secret` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `provider` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `redirect` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `personal_access_client` TINYINT(1) NOT NULL,
  `password_client` TINYINT(1) NOT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_clients_user_id_index` (`user_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5;


-- -----------------------------------------------------
-- Table `easytrack`.`oauth_personal_access_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`oauth_personal_access_clients` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`oauth_personal_access_clients` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3;


-- -----------------------------------------------------
-- Table `easytrack`.`oauth_refresh_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`oauth_refresh_tokens` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`oauth_refresh_tokens` (
  `id` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `access_token_id` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`products` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`products` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `code` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `description` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `brand` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `products_category_id_foreign` (`category_id` ASC),
  CONSTRAINT `products_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `easytrack`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 101;


-- -----------------------------------------------------
-- Table `easytrack`.`suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`suppliers` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`suppliers` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `site_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tel1` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `town` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `street` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tel2` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `suppliers_site_id_foreign` (`site_id` ASC),
  CONSTRAINT `suppliers_site_id_foreign`
    FOREIGN KEY (`site_id`)
    REFERENCES `easytrack`.`sites` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 41;


-- -----------------------------------------------------
-- Table `easytrack`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`orders` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`orders` (
  `supplier_id` BIGINT(20) UNSIGNED NOT NULL,
  `product_id` BIGINT(20) UNSIGNED NOT NULL,
  `bill_id` BIGINT(20) UNSIGNED NOT NULL,
  `site_id` BIGINT(20) NULL DEFAULT NULL,
  `quantity` INT(11) NOT NULL,
  `purchase_price` INT(11) NOT NULL,
  `status` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `orders_bill_id_foreign` (`bill_id` ASC),
  INDEX `orders_supplier_id_foreign` (`supplier_id` ASC),
  INDEX `orders_product_id_foreign` (`product_id` ASC),
  CONSTRAINT `orders_bill_id_foreign`
    FOREIGN KEY (`bill_id`)
    REFERENCES `easytrack`.`bills` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `easytrack`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_supplier_id_foreign`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `easytrack`.`suppliers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`password_resets` (
  `email` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `token` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `password_resets_email_index` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`permissions` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`permissions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34;


-- -----------------------------------------------------
-- Table `easytrack`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`roles` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`roles` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6;


-- -----------------------------------------------------
-- Table `easytrack`.`permission_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`permission_role` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`permission_role` (
  `role_id` BIGINT(20) UNSIGNED NOT NULL,
  `permission_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`role_id`, `permission_id`),
  INDEX `permission_role_permission_id_foreign` (`permission_id` ASC),
  CONSTRAINT `permission_role_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `easytrack`.`permissions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `permission_role_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `easytrack`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`permission_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`permission_user` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`permission_user` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `permission_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `permission_id`),
  INDEX `permission_user_permission_id_foreign` (`permission_id` ASC),
  CONSTRAINT `permission_user_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `easytrack`.`permissions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `permission_user_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `easytrack`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`product_site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`product_site` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`product_site` (
  `site_id` BIGINT(20) UNSIGNED NOT NULL,
  `product_id` BIGINT(20) UNSIGNED NOT NULL,
  `purchase_price` INT(11) NOT NULL,
  `selling_price` INT(11) NOT NULL,
  `initial_stock` INT(11) NOT NULL,
  `min` INT(11) NOT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `product_site_product_id_foreign` (`product_id` ASC),
  INDEX `product_site_site_id_foreign` (`site_id` ASC),
  CONSTRAINT `product_site_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `easytrack`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `product_site_site_id_foreign`
    FOREIGN KEY (`site_id`)
    REFERENCES `easytrack`.`sites` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`role_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`role_user` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`role_user` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `role_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `role_user_role_id_foreign` (`role_id` ASC),
  CONSTRAINT `role_user_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `easytrack`.`roles` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `role_user_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `easytrack`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`sales` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`sales` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `invoice_id` BIGINT(20) UNSIGNED NOT NULL,
  `product_id` BIGINT(20) UNSIGNED NOT NULL,
  `site_id` BIGINT(20) NULL DEFAULT NULL,
  `quantity` INT(11) NOT NULL,
  `selling_price` INT(11) NOT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `status` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `sales_invoice_id_foreign` (`invoice_id` ASC),
  INDEX `sales_product_id_foreign` (`product_id` ASC),
  CONSTRAINT `sales_invoice_id_foreign`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `easytrack`.`invoices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sales_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `easytrack`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`types` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`types` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `duration` INT(11) NOT NULL,
  `number_of_site` INT(11) NOT NULL,
  `number_of_employee` INT(11) NOT NULL,
  `price` INT(11) NOT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5;


-- -----------------------------------------------------
-- Table `easytrack`.`subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`subscriptions` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`subscriptions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `snack_id` BIGINT(20) UNSIGNED NOT NULL,
  `type_id` BIGINT(20) UNSIGNED NOT NULL,
  `end_date` DATETIME NOT NULL,
  `status` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `subscriptions_snack_id_foreign` (`snack_id` ASC),
  INDEX `subscriptions_type_id_foreign` (`type_id` ASC),
  CONSTRAINT `subscriptions_snack_id_foreign`
    FOREIGN KEY (`snack_id`)
    REFERENCES `easytrack`.`snacks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `subscriptions_type_id_foreign`
    FOREIGN KEY (`type_id`)
    REFERENCES `easytrack`.`types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
