-- MySQL Script generated by MySQL Workbench
-- Fri 17 Jul 2020 07:14:33 PM WAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema easytrack
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `easytrack` ;

-- -----------------------------------------------------
-- Schema easytrack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easytrack` DEFAULT CHARACTER SET latin1 ;
USE `easytrack` ;

-- -----------------------------------------------------
-- Table `easytrack`.`agendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`agendas` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`agendas` (
  `site_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `start` DATETIME NOT NULL,
  `status` ENUM('1', '0') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `end` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`purchases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`purchases` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`purchases` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `site_id` BIGINT(20) NOT NULL,
  `initiator` BIGINT(20) NOT NULL,
  `validator` BIGINT(20) NULL DEFAULT NULL,
  `code` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `shipping_price` DOUBLE NULL,
  `status` TINYINT NOT NULL DEFAULT '0',
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `paying_method` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `bills_code_unique` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`roles` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`roles` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `company_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8;


-- -----------------------------------------------------
-- Table `easytrack`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`users` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `username` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `tel` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `contact_tel` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `photo` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `address` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `bio` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `password` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `is_admin` TINYINT(1) NOT NULL DEFAULT 1,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles1_idx` (`role_id` ASC),
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `easytrack`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10;


-- -----------------------------------------------------
-- Table `easytrack`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`companies` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`companies` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `photo` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `tel1` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `tel2` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `town` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `street` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `snacks_name_unique` (`name` ASC),
  UNIQUE INDEX `snacks_slug_unique` (`slug` ASC),
  INDEX `snacks_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `snacks_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `easytrack`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8;


-- -----------------------------------------------------
-- Table `easytrack`.`sites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`sites` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`sites` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `companie_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tel1` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `tel2` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `town` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `street` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sites_name_unique` (`name` ASC),
  UNIQUE INDEX `sites_slug_unique` (`slug` ASC),
  INDEX `fk_sites_companies1_idx` (`companie_id` ASC),
  CONSTRAINT `fk_sites_companies1`
    FOREIGN KEY (`companie_id`)
    REFERENCES `easytrack`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 31;


-- -----------------------------------------------------
-- Table `easytrack`.`expense_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`expense_categories` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`expense_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `is_active` TINYINT NULL,
  `created_at` DATETIME NULL DEFAULT current_timestamp,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`expenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`expenses` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`expenses` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `site_id` BIGINT(20) UNSIGNED NOT NULL,
  `expense_category_id` INT NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `amount` INT(11) NOT NULL,
  `description` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `budgets_site_id_foreign` (`site_id` ASC),
  INDEX `fk_expenses_expenses_categories1_idx` (`expense_category_id` ASC),
  CONSTRAINT `budgets_site_id_foreign`
    FOREIGN KEY (`site_id`)
    REFERENCES `easytrack`.`sites` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_expenses_expenses_categories1`
    FOREIGN KEY (`expense_category_id`)
    REFERENCES `easytrack`.`expense_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`categories` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`categories` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `parent_id` INT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `categories_name_unique` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6;


-- -----------------------------------------------------
-- Table `easytrack`.`failed_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`failed_jobs` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `connection` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `queue` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `payload` LONGTEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `exception` LONGTEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`sales` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`sales` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `site_id` BIGINT(20) NOT NULL,
  `initiator` BIGINT(20) NOT NULL,
  `validator` BIGINT(20) NOT NULL,
  `code` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `is_active` TINYINT NOT NULL DEFAULT '1',
  `status` TINYINT NOT NULL DEFAULT '0',
  `shipping_cost` DOUBLE NULL,
  `sale_note` TEXT NULL,
  `seller_note` TEXT NULL,
  `paying_method` VARCHAR(45) NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`messages` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`messages` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sender` INT(11) NOT NULL,
  `receiver` INT(11) NOT NULL,
  `status` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '0',
  `message` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `file` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`migrations` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32;


-- -----------------------------------------------------
-- Table `easytrack`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`notifications` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`notifications` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `site_id` BIGINT(20) NULL DEFAULT NULL,
  `snack_id` BIGINT(20) NULL DEFAULT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  `type` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `text` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `status` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `action` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`oauth_access_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`oauth_access_tokens` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`oauth_access_tokens` (
  `id` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `client_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `scopes` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_access_tokens_user_id_index` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`oauth_auth_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`oauth_auth_codes` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`oauth_auth_codes` (
  `id` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `client_id` BIGINT(20) UNSIGNED NOT NULL,
  `scopes` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_auth_codes_user_id_index` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`oauth_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`oauth_clients` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`oauth_clients` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `secret` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `provider` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `redirect` TEXT COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `personal_access_client` TINYINT(1) NOT NULL,
  `password_client` TINYINT(1) NOT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_clients_user_id_index` (`user_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3;


-- -----------------------------------------------------
-- Table `easytrack`.`oauth_personal_access_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`oauth_personal_access_clients` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`oauth_personal_access_clients` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2;


-- -----------------------------------------------------
-- Table `easytrack`.`oauth_refresh_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`oauth_refresh_tokens` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`oauth_refresh_tokens` (
  `id` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `access_token_id` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`units` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `base_unit` VARCHAR(45) NULL,
  `operator` VARCHAR(45) NULL,
  `operator_value` DOUBLE NULL,
  `is_active` TINYINT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`taxes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`taxes` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`taxes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `rate` DOUBLE NULL,
  `is_active` TINYINT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`products` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`products` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `taxe_id` INT NOT NULL,
  `unit_id` INT NOT NULL,
  `category_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `code` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `description` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `brand` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `type` VARCHAR(45) NULL,
  `barcode_symbology` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `products_category_id_foreign` (`category_id` ASC),
  INDEX `fk_products_units1_idx` (`unit_id` ASC),
  INDEX `fk_products_taxes1_idx` (`taxe_id` ASC),
  CONSTRAINT `products_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `easytrack`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products_units1`
    FOREIGN KEY (`unit_id`)
    REFERENCES `easytrack`.`units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_taxes1`
    FOREIGN KEY (`taxe_id`)
    REFERENCES `easytrack`.`taxes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 101;


-- -----------------------------------------------------
-- Table `easytrack`.`suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`suppliers` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`suppliers` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `site_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `phone2` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `town` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `street` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `phone1` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `photo` VARCHAR(45) NULL,
  `company_name` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `suppliers_site_id_foreign` (`site_id` ASC),
  CONSTRAINT `suppliers_site_id_foreign`
    FOREIGN KEY (`site_id`)
    REFERENCES `easytrack`.`sites` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 41;


-- -----------------------------------------------------
-- Table `easytrack`.`product_purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`product_purchase` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`product_purchase` (
  `supplier_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `purchase_id` INT UNSIGNED NOT NULL,
  `site_id` INT NULL DEFAULT NULL,
  `qty` INT(11) NOT NULL,
  `damages` INT(11) NOT NULL DEFAULT '0',
  `cost` DOUBLE NOT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `purchase_unit_id` INT NULL,
  INDEX `orders_bill_id_foreign` (`purchase_id` ASC),
  INDEX `orders_supplier_id_foreign` (`supplier_id` ASC),
  INDEX `orders_product_id_foreign` (`product_id` ASC),
  CONSTRAINT `orders_bill_id_foreign`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `easytrack`.`purchases` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `easytrack`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_supplier_id_foreign`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `easytrack`.`suppliers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`password_resets` (
  `email` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `token` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `password_resets_email_index` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`permissions` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`permissions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `slug` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` TEXT COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34;


-- -----------------------------------------------------
-- Table `easytrack`.`permission_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`permission_role` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`permission_role` (
  `role_id` BIGINT(20) UNSIGNED NOT NULL,
  `permission_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`role_id`, `permission_id`),
  INDEX `permission_role_permission_id_foreign` (`permission_id` ASC),
  CONSTRAINT `permission_role_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `easytrack`.`permissions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `permission_role_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `easytrack`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`permission_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`permission_user` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`permission_user` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `permission_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `permission_id`),
  INDEX `permission_user_permission_id_foreign` (`permission_id` ASC),
  CONSTRAINT `permission_user_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `easytrack`.`permissions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `permission_user_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `easytrack`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`product_site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`product_site` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`product_site` (
  `site_id` BIGINT(20) UNSIGNED NOT NULL,
  `product_id` BIGINT(20) UNSIGNED NOT NULL,
  `cost` INT(11) NOT NULL,
  `price` INT(11) NOT NULL,
  `qty` INT(11) NOT NULL,
  `qty_alert` INT(11) NOT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `promotion` TINYINT NULL DEFAULT 0,
  `promotion_price` INT NULL,
  `promotion_start` DATE NULL,
  `promotion_end` DATE NULL,
  `tax_method` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `product_site_product_id_foreign` (`product_id` ASC),
  INDEX `product_site_site_id_foreign` (`site_id` ASC),
  CONSTRAINT `product_site_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `easytrack`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `product_site_site_id_foreign`
    FOREIGN KEY (`site_id`)
    REFERENCES `easytrack`.`sites` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`product_sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`product_sale` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`product_sale` (
  `sale_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `site_id` BIGINT(20) NULL DEFAULT NULL,
  `quantity` INT(11) NOT NULL,
  `price` INT(11) NOT NULL,
  `is_active` TINYINT NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `sale_unit_id` INT NULL,
  INDEX `sales_invoice_id_foreign` (`sale_id` ASC),
  INDEX `sales_product_id_foreign` (`product_id` ASC),
  CONSTRAINT `sales_invoice_id_foreign`
    FOREIGN KEY (`sale_id`)
    REFERENCES `easytrack`.`sales` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sales_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `easytrack`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`types` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`types` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(191) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `duration` INT(11) NOT NULL,
  `number_of_site` INT(11) NOT NULL,
  `number_of_employee` INT(11) NOT NULL,
  `price` INT(11) NOT NULL,
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5;


-- -----------------------------------------------------
-- Table `easytrack`.`subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`subscriptions` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`subscriptions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT(20) UNSIGNED NOT NULL,
  `type_id` BIGINT(20) UNSIGNED NOT NULL,
  `end_date` DATETIME NOT NULL,
  `status` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `active` ENUM('0', '1') COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `subscriptions_snack_id_foreign` (`company_id` ASC),
  INDEX `subscriptions_type_id_foreign` (`type_id` ASC),
  CONSTRAINT `subscriptions_snack_id_foreign`
    FOREIGN KEY (`company_id`)
    REFERENCES `easytrack`.`companies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `subscriptions_type_id_foreign`
    FOREIGN KEY (`type_id`)
    REFERENCES `easytrack`.`types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`customers` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `company_name` VARCHAR(45) NULL,
  `town` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `is_active` TINYINT NULL,
  `created_at` VARCHAR(45) NULL DEFAULT 'current_timestamp',
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`employees` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `site_id` BIGINT(20) UNSIGNED NOT NULL,
  `cni_number` VARCHAR(45) NULL,
  `contact_name` VARCHAR(45) NULL,
  `contact_phone` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT current_timestamp,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employees_users1_idx` (`user_id` ASC),
  INDEX `fk_employees_sites1_idx` (`site_id` ASC),
  CONSTRAINT `fk_employees_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `easytrack`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_sites1`
    FOREIGN KEY (`site_id`)
    REFERENCES `easytrack`.`sites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`holydays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`holydays` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`holydays` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `is_approuved` TINYINT NULL,
  `created_at` DATETIME NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`langages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`langages` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`langages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easytrack`.`payrools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easytrack`.`payrools` ;

CREATE TABLE IF NOT EXISTS `easytrack`.`payrools` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NULL,
  `user_id` INT NULL,
  `amount` DOUBLE NULL,
  `paying_method` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `created_at` DATETIME NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
